services:
  learning_path:
    build: .
    container_name: learning_path
    restart: unless-stopped
    ports:
      - "8765:3000"
    environment:
      - DATA_DIR=/data
    volumes:
      - /your/data/directory:/data
